import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from 'src/environments/environment';
import { IMenu } from '../models/menu.model';

@Injectable({
  providedIn: 'root',
})
export class MenuService {
  menuList: IMenu[] = [     
    {
      key: ' PROFILE',
      title: 'Profile',
      localTitle: 'প্রোফাইল',
      enabled: true,
      imagePath: `assets/icons/Menu/ic_account_balance.png`,
      url: '/profile/detailprofile',
    },
    {
      key: 'ACCOUNTS',
      title: 'Accounts',
      localTitle: 'হিসাব সমূহ',
      enabled: true,     
      imagePath: `assets/icons/Menu/Account summary.png`,
      //url: '/account',
      children: [
        {
          key: 'ACCOUNT-DETAILS',
          title: 'Account Details',
          localTitle: '',
          enabled: true,
          // imagePath: `assets/icons/Menu/Account details.png`,
          imagePath: `assets/icons/Menu/Account details.png`,
          url: '/account/account-details',
        },
        // {
        //   key: 'ACCOUNT-SUMMARY',
        //   title: 'Account Summary',
        //   localTitle: '',
        //   enabled: true,
        //   imagePath: `assets/icons/Menu/Account summary.png`,
        //   url: '/account/account-summary',
        // },
        {
          key: 'STATEMENT',
          title: 'Statement',
          localTitle: '',
          enabled: true,
          imagePath: `assets/icons/Menu/Statement.png`,
          url: '/account/statement',
        },
        {
          key: 'ACCOUNT-OPEN',
          title: 'New FDR/Scheme',
          localTitle: '',
          enabled: true,
          imagePath: `assets/icons/Menu/New Account.png`,
          url: '/account/account-open',
        },
        // {
        //   key: 'ENCASHMENT-REQUEST',
        //   title: 'Encashment',
        //   localTitle: '',
        //   enabled: true,
        //   imagePath: `assets/icons/Menu/Encashment.png`,
        //   url: '/account/encashment',
        // },
        {
          key: 'ACCOUNT-OPENING-RECEIPT',
          title: 'Account Opening Receipt',
          localTitle: '',
          enabled: true,
          imagePath: `assets/icons/Menu/Statement.png`,
          url: '/account/account-opening-receipt',
        },
        // {
        //   key: 'FINANCIAL-TRANSACTION-DETAILS',
        //   title: 'Financial Transaction',
        //   localTitle: '',
        //   enabled: true,
        //   imagePath: `assets/icons/Menu/ic_fund_transfer.png`,
        //   url: '/account/financial-transactions',
        // },
      ],
    },
    // {
    //   key: 'LOAN',
    //   title: 'Loan',
    //   localTitle: '',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_benefits.png`,
    //   // url: '/investment',
    //   children: [
    //     {
    //       key: 'LOAN_APPLICATION',
    //       title: 'Loan Application',
    //       localTitle: '',
    //       enabled: true,
    //       imagePath: `assets/icons/Menu/ic_benefits.png`,
    //       url: '/investment',
    //     },
    //     {
    //       key: 'LOAN_LOG',
    //       title: 'Application History',
    //       localTitle: '',
    //       enabled: true,
    //       imagePath: `assets/icons/Menu/ic_instructions.png`,
    //       url: '/investment/log',
    //     },
    //   ]
    // },
    {
      key: 'SERVICES',
      title: 'Requests',
      localTitle: 'রিকোয়েষ্টস',
      enabled: true,
      imagePath: `assets/icons/Menu/ic_request.png`,
      // url: '',
      children: [
        {
          key: 'ADDRESS_CHANGE',
          title: 'Address Change',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/Adress Change.png`,
          url: '/myservices/addresschangerequest',
          //addresschangerequest
        },
        // {
        //   key: 'BANK_GUARANTEE',
        //   title: 'Bank Guarantee',
        //   localTitle: 'নির্দেশনা',
        //   enabled: true,
        //   imagePath: `assets/icons/Menu/ic_instructions.png',
        //   url: '/myservices/bankguaranteerequest',
        // },
        {
          key: 'CHEQUEBOOK',
          title: 'Chequebook',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/Chequebook.png`,
          url: '/myservices/chequebookrequest',
        },
        {
          key: 'COMPLAIN',
          title: 'Complain',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/Statement.png`,
          url: '/myservices/complainrequest',
        },
        {
          key: 'INSTRUCTION',
          title: 'Instruction',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/ic_instructions.png`,
          url: '/transactions/standinginstruction',
        }, 
        // {
        //   key: 'LOST_CARD',
        //   title: 'Lost Card',
        //   localTitle: 'নির্দেশনা',
        //   enabled: true,
        //   imagePath: `assets/icons/Menu/ic_instructions.png`,
        //   url: '/myservices/lostcardrequest',
        // },
        {
          key: 'PAPERCERTIFICATE',
          title: 'Paper Certificate',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/Statement.png`,
          url: '/myservices/papercertificaterequest',
        },
        {
          key: 'PAYORDER',
          title: 'Pay Order',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/Chequebook.png`,
          url: '/myservices/payorderrequest',
        },
        {
          key: 'POSITIVEPAY',
          title: 'Positive Pay',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/Chequebook.png`,
          url: '/myservices/positivepayrequest',
        },
        // {
        //   key: 'LC',
        //   title: 'LC Request',
        //   localTitle: 'নির্দেশনা',
        //   enabled: true,
        //   imagePath: `assets/icons/Menu/ic_instructions.png`,
        //   url: '/myservices/lcrequest',
        // },
        // {
        //   key: 'STATEMENT',
        //   title: 'Statement',
        //   localTitle: 'নির্দেশনা',
        //   enabled: true,
        //   imagePath: `assets/icons/Menu/Statement.png`,
        //   url: '/myservices/statementrequest',
        // },
        {
          key: 'STOP_CHEQUE',
          title: 'Stop Cheque',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/Stop Cheque.png`,
          url: '/myservices/stopchequerequest',
        }, 
        
      ],
    },
    // {
    //   key: 'BENEFITS',
    //   title: 'Benefits',
    //   localTitle: 'বেনিফিটস',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_benefits.png`,
    //   url: '/otherservices/benefits',
    // },
    
    // {
    //   key: 'ZIPPARTNERS',
    //   title: 'Merchants',
    //   localTitle: 'মার্সেন্টস',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_merchants.png`,
    //   url: '/otherservices/partners',
    // },
    {
      key: 'HISTORY',
      title: 'History',
      localTitle: 'নির্দেশনা',
      enabled: true,
      imagePath: `assets/icons/Menu/ic_instructions.png`,
      // url: '/myservices/request-log',
      children: [
        {
          key: 'FINANCIAL-TRANSACTION-DETAILS',
          title: 'Fund Transfer Log',
          localTitle: '',
          enabled: true,
          imagePath: `assets/icons/Menu/ic_fund_transfer.png`,
          url: '/account/financial-transactions',
        },
        {
          key: 'TRANSACTION-RECEIPT',
          title: 'Transaction receipt',
          localTitle: '',
          enabled: true,
          imagePath: `assets/icons/Menu/Statement.png`,
          url: '/account/transaction-receipt',
        },
        {
          key: 'REQUEST_LOG',
          title: 'Request Log',
          localTitle: 'নির্দেশনা',
          enabled: true,
          imagePath: `assets/icons/Menu/Request log.png`,
          url: '/myservices/request-log',
        },
        {
          key: 'USERACTIVITY',
          title: 'Activity Log',
          localTitle: '',
          enabled: true,
          imagePath: `assets/icons/Menu/ic_instructions.png`,
          url: '/activity/useractivity',
        },
      ],
    },
    {
      key: ' BENEFICIARY',
      title: 'Beneficiary',
      localTitle: 'কিউআর পে',
      enabled: true,
      imagePath: `assets/icons/Menu/ic_qr_cash.png`,
      url: '/transactions/beneficiary',
    },
    {
      key: 'TRANSFER',
      title: 'Fund Transfer',
      localTitle: 'হস্তান্তর',
      enabled: true,
      imagePath: `assets/icons/Menu/ic_fund_transfer.png`,
      url: '/transactions/fundtransfer',
    },
    // {
    //   key: 'BANGLAQR',
    //   title: 'Payment',
    //   localTitle: 'হস্তান্তর',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/Bangla_QR.png`,
    //   url: '/transactions/bangla-qr',
    // },
    {
      key: 'TOPUP',
      title: 'Top Up',
      localTitle: '',
      enabled: true,
      imagePath: `assets/icons/Menu/ic_action_topup.png`,
      url: '/topup',
    },
    {
      key: 'UTILITY_BILLS',
      title: 'Bill Pay',
      localTitle: 'বিল পে',
      enabled: true,
      imagePath: `assets/icons/Menu/ic_bill_payment.png`,
      url: '/utility/billpayment',
    },
    
    // {
    //   key: 'NOTIFICATION',
    //   title: 'Nofifications',
    //   localTitle: 'নোটিফিকেশনস',
    //   enabled: false,
    //   imagePath: `assets/icons/Menu/ic_notifications.png',
    //   url: '/otherservices/notifications',
    // },
    // {
    //   key: 'INSTRUCTION',
    //   title: 'Instruction',
    //   localTitle: 'নির্দেশনা',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_instructions.png',
    //   url: '/transactions/standinginstruction',
    // },

    // {
    //   key: 'TOPUPS',
    //   title: 'TopUp',
    //   localTitle: 'টপআপ',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_action_topup.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'TUTIONFEES',
    //   title: 'Tution Fees',
    //   localTitle: 'টিউশন ফিস',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_account_balance.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'CREDITCARD',
    //   title: 'Credit Card',
    //   localTitle: 'ক্রেডিট কার্ড',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_action_topup.png',
    //   url: '/transactions/fundtransfer',
    // },

    // {
    //   key: 'DEPOSIT_SLIP',
    //   title: 'Deposit Slip',
    //   localTitle: 'ডিপোজিট স্লিপ',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_action_topup.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'LOCATION',
    //   title: 'Locations',
    //   localTitle: 'লোকেশনস',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_location.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'EMICALC',
    //   title: 'EMI Calc',
    //   localTitle: 'ইএমআই ক্যাল',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_action_topup.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'EXCHANGERATE',
    //   title: 'TopUp',
    //   localTitle: 'টপআপ',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_action_topup.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'NOTIFICATION',
    //   title: 'Nofifications',
    //   localTitle: 'নোটিফিকেশনস',
    //   enabled: false,
    //   imagePath: `assets/icons/Menu/ic_notifications.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'MESSAGECENTER',
    //   title: 'Msg Center',
    //   localTitle: 'ম্যাসেজ সেন্টার',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_notifications.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'NEWS_N_EVENTS',
    //   title: 'News',
    //   localTitle: 'নিউজ',
    //   enabled: false,
    //   imagePath: `assets/icons/Menu/ic_new_events.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'PRODUCTS',
    //   title: 'Products',
    //   localTitle: 'প্রোডাক্টস',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_product.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'BENEFITS',
    //   title: 'Benefits',
    //   localTitle: 'বেনিফিটস',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_benefits.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'ZIPPARTNERS',
    //   title: 'Merchants',
    //   localTitle: 'মার্সেন্টস',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_notifications.png',
    //   url: '/transactions/fundtransfer',
    // },
    // {
    //   key: 'CHANGE-PASSWORD',
    //   title: 'Change Password',
    //   localTitle: 'ইনফো',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_notifications.png',
    //   url: '/account/changepassword',
    // },
    // {
    //   key: 'USERACTIVITY',
    //   title: 'Activity Log',
    //   localTitle: '',
    //   enabled: true,
    //   imagePath: `assets/icons/Menu/ic_instructions.png',
    //   url: '/activity/useractivity',
    // },
  ];

  constructor() {}

  getMainMenu(): IMenu[] {
    return this.menuList;
  }
}
